# Generated by Django 5.2.6 on 2025-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='article_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
