# Generated by Django 5.2.6 on 2025-09-24 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_article_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
